# Generated by Django 5.2.16 on 2026-07-20 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("whatsapp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="whatsappconversation",
            name="bhk",
            field=models.CharField(blank=True, default="", max_length=20),
        ),
        migrations.AddField(
            model_name="whatsappconversation",
            name="budget_bracket",
            field=models.CharField(blank=True, default="", max_length=64),
        ),
        migrations.AddField(
            model_name="whatsappconversation",
            name="locality",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="whatsappconversation",
            name="purpose",
            field=models.CharField(blank=True, default="", max_length=32),
        ),
        migrations.AlterField(
            model_name="whatsappconversation",
            name="state",
            field=models.CharField(
                choices=[
                    ("start", "Start"),
                    ("awaiting_purpose", "Awaiting purpose"),
                    ("awaiting_bhk", "Awaiting BHK"),
                    ("awaiting_budget", "Awaiting budget"),
                    ("awaiting_locality", "Awaiting locality"),
                    ("completed", "Completed"),
                    ("handed_off", "Handed off"),
                ],
                default="start",
                max_length=32,
            ),
        ),
    ]
