services:
  - type: web
    name: leadrescue
    env: python
    buildCommand: pip install -r requirements.txt && cd leadrescue && python manage.py collectstatic --noinput
    startCommand: cd leadrescue && python manage.py migrate --noinput && gunicorn config.wsgi --bind 0.0.0.0:$PORT
    envVars:
      - key: PYTHON_VERSION
        value: "3.13"
      - key: DJANGO_SETTINGS_MODULE
        value: "config.settings"
      - key: DEBUG
        value: "False"
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: leadrescue-db
          property: connectionString
      - key: ALLOWED_HOSTS
        value: ".onrender.com"
      - key: REDIS_URL
        fromService:
          type: redis
          name: leadrescue-redis
          property: connectionString
      - key: CELERY_BROKER_URL
        fromService:
          type: redis
          name: leadrescue-redis
          property: connectionString
      - key: CELERY_RESULT_BACKEND
        fromService:
          type: redis
          name: leadrescue-redis
          property: connectionString
      - key: WHATSAPP_APP_ID
        sync: false
      - key: WHATSAPP_APP_SECRET
        sync: false
      - key: WHATSAPP_WEBHOOK_VERIFY_TOKEN
        sync: false
      - key: FIELD_ENCRYPTION_KEY
        generateValue: true
      - key: ADMIN_URL
        value: "harsh-admin/"

  - type: worker
    name: leadrescue-celery
    env: python
    buildCommand: pip install -r requirements.txt && cd leadrescue && python manage.py collectstatic --noinput
    startCommand: cd leadrescue && celery -A config worker --loglevel=info
    envVars:
      - key: PYTHON_VERSION
        value: "3.13"
      - key: DJANGO_SETTINGS_MODULE
        value: "config.settings"
      - key: DEBUG
        value: "False"
      - key: SECRET_KEY
        fromService:
          type: web
          name: leadrescue
          envVarKey: SECRET_KEY
      - key: DATABASE_URL
        fromDatabase:
          name: leadrescue-db
          property: connectionString
      - key: REDIS_URL
        fromService:
          type: redis
          name: leadrescue-redis
          property: connectionString
      - key: CELERY_BROKER_URL
        fromService:
          type: redis
          name: leadrescue-redis
          property: connectionString
      - key: CELERY_RESULT_BACKEND
        fromService:
          type: redis
          name: leadrescue-redis
          property: connectionString
      - key: WHATSAPP_APP_ID
        sync: false
      - key: WHATSAPP_APP_SECRET
        sync: false
      - key: WHATSAPP_WEBHOOK_VERIFY_TOKEN
        sync: false
      - key: FIELD_ENCRYPTION_KEY
        sync: false
      - key: ADMIN_URL
        value: "harsh-admin/"

  - type: redis
    name: leadrescue-redis
    plan: free
    ipAllowList: []

databases:
  - name: leadrescue-db
    plan: free
    databaseName: leadrescue
    user: leadrescue
