# Generated by Django 5.2.16 on 2026-07-21 05:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0004_agentinvite"),
        ("agencies", "0005_rename_pro_to_growth"),
    ]

    operations = [
        migrations.CreateModel(
            name="UpgradeRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "requested_plan",
                    models.CharField(
                        choices=[("starter", "Starter"), ("growth", "Growth")],
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("LINK_SENT", "Link Sent"),
                            ("PAID", "Paid"),
                            ("ACTIVATED", "Activated"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                (
                    "razorpay_payment_link_id",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "razorpay_payment_link_url",
                    models.URLField(blank=True, max_length=1024, null=True),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("paid_at", models.DateTimeField(blank=True, null=True)),
                ("activated_at", models.DateTimeField(blank=True, null=True)),
                (
                    "agency",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="upgrade_requests",
                        to="agencies.agency",
                    ),
                ),
                (
                    "requested_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="accounts.agentprofile",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
