# Generated by Django 5.2.16 on 2026-07-17 17:14

from django.db import migrations, models
from django.utils.text import slugify


def populate_agency_slugs(apps, schema_editor):
    """Populate slug for existing Agency rows before adding unique constraint."""
    Agency = apps.get_model("agencies", "Agency")
    used_slugs = set()
    for agency in Agency.objects.all():
        base_slug = slugify(agency.name) or "agency"
        slug = base_slug
        counter = 1
        while slug in used_slugs:
            slug = f"{base_slug}-{counter}"
            counter += 1
        used_slugs.add(slug)
        agency.slug = slug
        agency.save(update_fields=["slug"])


class Migration(migrations.Migration):

    dependencies = [
        ("agencies", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="agency",
            options={"verbose_name_plural": "agencies"},
        ),
        migrations.RemoveField(
            model_name="agency",
            name="subscription_status",
        ),
        migrations.AddField(
            model_name="agency",
            name="brand_logo",
            field=models.ImageField(blank=True, null=True, upload_to="agency_logos/"),
        ),
        migrations.AddField(
            model_name="agency",
            name="brand_primary_color",
            field=models.CharField(blank=True, default="#B87333", max_length=7),
        ),
        migrations.AddField(
            model_name="agency",
            name="plan_tier",
            field=models.CharField(
                choices=[("free", "Free"), ("starter", "Starter"), ("pro", "Pro")],
                default="free",
                max_length=20,
            ),
        ),
        # Step 1: Add slug WITHOUT unique constraint
        migrations.AddField(
            model_name="agency",
            name="slug",
            field=models.SlugField(blank=True, max_length=255, default="", db_index=False),
        ),
        # Step 2: Populate slugs for existing rows
        migrations.RunPython(populate_agency_slugs, migrations.RunPython.noop),
        # Step 3: Now apply the unique constraint
        migrations.AlterField(
            model_name="agency",
            name="slug",
            field=models.SlugField(blank=True, max_length=255, unique=True),
        ),
    ]
