# Generated by Django 5.2.16 on 2026-07-20 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agencies", "0003_agency_whatsapp_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="agency",
            name="budget_brackets",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="List of budget brackets e.g. ['Under 50L', '50L–1Cr', '1Cr–2Cr', '2Cr+']",
            ),
        ),
    ]
