# Generated by Django 5.2.16 on 2026-07-21 05:14

from django.db import migrations, models


def update_pro_to_growth(apps, schema_editor):
    Agency = apps.get_model("agencies", "Agency")
    Agency.objects.filter(plan_tier="pro").update(plan_tier="growth")

class Migration(migrations.Migration):

    dependencies = [
        ("agencies", "0004_add_budget_brackets"),
    ]

    operations = [
        migrations.RunPython(update_pro_to_growth, reverse_code=migrations.RunPython.noop),
        migrations.AlterField(
            model_name="agency",
            name="plan_tier",
            field=models.CharField(
                choices=[
                    ("free", "Free"),
                    ("starter", "Starter"),
                    ("growth", "Growth"),
                ],
                default="free",
                max_length=20,
            ),
        ),
    ]
