# Generated by Django 5.2.16 on 2026-07-21 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agencies", "0006_migrate_free_to_starter"),
    ]

    operations = [
        migrations.AlterField(
            model_name="agency",
            name="plan_tier",
            field=models.CharField(
                choices=[("starter", "Starter"), ("growth", "Growth")],
                default="starter",
                max_length=20,
            ),
        ),
    ]
