# Generated by Django 5.2.16 on 2026-07-21 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agencies", "0007_alter_agency_plan_tier"),
    ]

    operations = [
        migrations.AlterField(
            model_name="agency",
            name="plan_tier",
            field=models.CharField(
                choices=[
                    ("free", "Free"),
                    ("starter", "Starter"),
                    ("growth", "Growth"),
                ],
                default="free",
                max_length=20,
            ),
        ),
    ]
