# Generated by Django 5.2.16 on 2026-07-16 16:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("agencies", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Property",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("bhk", models.CharField(max_length=50)),
                ("price", models.DecimalField(decimal_places=2, max_digits=12)),
                ("location", models.CharField(max_length=255)),
                ("city", models.CharField(max_length=100)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("available", "Available"),
                            ("sold", "Sold"),
                            ("on_hold", "On Hold"),
                        ],
                        default="available",
                        max_length=20,
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="property_images/"
                    ),
                ),
                ("description", models.TextField(blank=True)),
                (
                    "agency",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="properties",
                        to="agencies.agency",
                    ),
                ),
            ],
        ),
    ]
