# Generated by Django 5.2.16 on 2026-07-17 17:18

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_agentprofile_avatar_agentprofile_is_active_and_more"),
        ("properties", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="property",
            options={"verbose_name_plural": "properties"},
        ),
        migrations.AddField(
            model_name="property",
            name="address",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AddField(
            model_name="property",
            name="assigned_agent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="properties",
                to="accounts.agentprofile",
            ),
        ),
        migrations.AddField(
            model_name="property",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="property",
            name="listing_type",
            field=models.CharField(
                choices=[("sale", "Sale"), ("rent", "Rent")],
                default="sale",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="property",
            name="locality",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="property",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="property",
            name="bhk",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name="property",
            name="city",
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="property",
            name="location",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="property",
            name="status",
            field=models.CharField(
                choices=[
                    ("available", "Available"),
                    ("pending", "Pending"),
                    ("sold", "Sold"),
                    ("rented", "Rented"),
                ],
                default="available",
                max_length=20,
            ),
        ),
    ]
