# Generated by Django 5.2.16 on 2026-07-17 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("properties", "0002_alter_property_options_property_address_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="property",
            name="amenities",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="property",
            name="area_sqft",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="property",
            name="builder",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="property",
            name="project_name",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="property",
            name="bhk",
            field=models.CharField(
                blank=True,
                choices=[
                    ("studio", "Studio"),
                    ("1_bhk", "1 BHK"),
                    ("2_bhk", "2 BHK"),
                    ("3_bhk", "3 BHK"),
                    ("4_bhk", "4 BHK"),
                    ("4_plus_bhk", "4+ BHK"),
                ],
                max_length=20,
                null=True,
            ),
        ),
    ]
