# Generated by Django 5.2.16 on 2026-07-20 15:28

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("properties", "0004_propertyimage"),
    ]

    operations = [
        migrations.AddField(
            model_name="property",
            name="brochure_pdf",
            field=cloudinary.models.CloudinaryField(
                blank=True, max_length=255, null=True, verbose_name="brochure"
            ),
        ),
    ]
