# Generated by Django 5.2.16 on 2026-07-19 12:03

import cloudinary_storage.storage
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("imports", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="importjob",
            name="file",
            field=models.FileField(
                storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(),
                upload_to="imports/%Y/%m/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["csv", "xls", "xlsx"]
                    )
                ],
            ),
        ),
    ]
