# Generated by Django 5.2.16 on 2026-07-19 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("imports", "0002_alter_importjob_file"),
    ]

    operations = [
        migrations.AddField(
            model_name="importjob",
            name="cached_headers",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="importjob",
            name="file_url",
            field=models.URLField(blank=True, default="", max_length=500),
        ),
    ]
