# Generated by Django 5.2.16 on 2026-07-19 14:46

import apps.imports.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("imports", "0003_importjob_cached_headers_importjob_file_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="importjob",
            name="file",
            field=models.FileField(
                storage=apps.imports.models.ImportFileStorage(),
                upload_to="imports/%Y/%m/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["csv", "xls", "xlsx"]
                    )
                ],
            ),
        ),
    ]
