# Generated by Django 5.2.16 on 2026-07-19 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("imports", "0004_alter_importjob_file"),
    ]

    operations = [
        migrations.AlterField(
            model_name="importjob",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("mapping", "Mapping"),
                    ("processing", "Processing"),
                    ("completed", "Completed"),
                    ("failed", "Failed"),
                    ("canceled", "Canceled"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
