# Generated by Django 5.2.16 on 2026-07-17 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="agentprofile",
            name="avatar",
            field=models.ImageField(blank=True, null=True, upload_to="agent_avatars/"),
        ),
        migrations.AddField(
            model_name="agentprofile",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="agentprofile",
            name="role",
            field=models.CharField(
                choices=[("owner", "Owner"), ("agent", "Agent"), ("admin", "Admin")],
                default="agent",
                max_length=20,
            ),
        ),
    ]
