# Generated by Django 5.2.16 on 2026-07-18 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_agentprofile_avatar_agentprofile_is_active_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="agentprofile",
            name="welcome_email_sent",
            field=models.BooleanField(default=False),
        ),
    ]
