# Generated by Django 5.2.16 on 2026-07-16 16:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
        ("agencies", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Lead",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("phone", models.CharField(max_length=20)),
                ("source", models.CharField(max_length=100)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("New", "New"),
                            ("Contacted", "Contacted"),
                            ("Site Visit", "Site Visit"),
                            ("Negotiation", "Negotiation"),
                            ("Closed Won", "Closed Won"),
                            ("Closed Lost", "Closed Lost"),
                        ],
                        default="New",
                        max_length=20,
                    ),
                ),
                ("budget", models.CharField(blank=True, max_length=100)),
                ("bhk_preference", models.CharField(blank=True, max_length=50)),
                ("area_preference", models.CharField(blank=True, max_length=255)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("last_contacted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "agency",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="leads",
                        to="agencies.agency",
                    ),
                ),
                (
                    "agent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="leads",
                        to="accounts.agentprofile",
                    ),
                ),
            ],
        ),
    ]
