# Generated by Django 5.2.16 on 2026-07-17 17:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_agentprofile_avatar_agentprofile_is_active_and_more"),
        ("agencies", "0002_alter_agency_options_and_more"),
        ("leads", "0001_initial"),
        ("properties", "0002_alter_property_options_property_address_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Activity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "activity_type",
                    models.CharField(
                        choices=[
                            ("call", "Call"),
                            ("email", "Email"),
                            ("note", "Note"),
                            ("whatsapp", "WhatsApp"),
                            ("status_change", "Status Change"),
                        ],
                        max_length=20,
                    ),
                ),
                ("content", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name_plural": "activities",
            },
        ),
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("due_date", models.DateTimeField()),
                ("is_completed", models.BooleanField(default=False)),
                ("note", models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.RenameField(
            model_name="lead",
            old_name="agent",
            new_name="assigned_agent",
        ),
        migrations.AddField(
            model_name="lead",
            name="email",
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name="lead",
            name="linked_property",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="leads",
                to="properties.property",
            ),
        ),
        migrations.AddField(
            model_name="lead",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="lead",
            name="source",
            field=models.CharField(
                choices=[
                    ("website", "Website"),
                    ("referral", "Referral"),
                    ("google", "Google"),
                    ("manual", "Manual"),
                    ("whatsapp", "WhatsApp"),
                ],
                default="manual",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="lead",
            name="status",
            field=models.CharField(
                choices=[
                    ("new", "New"),
                    ("contacted", "Contacted"),
                    ("qualified", "Qualified"),
                    ("site_visit", "Site Visit"),
                    ("negotiation", "Negotiation"),
                    ("converted", "Converted"),
                    ("lost", "Lost"),
                ],
                default="new",
                max_length=20,
            ),
        ),
        migrations.AddIndex(
            model_name="lead",
            index=models.Index(
                fields=["agency", "status"], name="lead_agency_status_idx"
            ),
        ),
        migrations.AddField(
            model_name="activity",
            name="agency",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="activities",
                to="agencies.agency",
            ),
        ),
        migrations.AddField(
            model_name="activity",
            name="agent",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="activities",
                to="accounts.agentprofile",
            ),
        ),
        migrations.AddField(
            model_name="activity",
            name="lead",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="activities",
                to="leads.lead",
            ),
        ),
        migrations.AddField(
            model_name="activity",
            name="property",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="activities",
                to="properties.property",
            ),
        ),
        migrations.AddField(
            model_name="task",
            name="assigned_agent",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tasks",
                to="accounts.agentprofile",
            ),
        ),
        migrations.AddField(
            model_name="task",
            name="lead",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tasks",
                to="leads.lead",
            ),
        ),
    ]
