# Generated by Django 5.2.16 on 2026-07-17 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leads", "0002_activity_task_rename_agent_lead_assigned_agent_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="lead",
            name="budget_max",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=12, null=True
            ),
        ),
        migrations.AddField(
            model_name="lead",
            name="budget_min",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=12, null=True
            ),
        ),
        migrations.AddField(
            model_name="lead",
            name="preferred_bhk",
            field=models.CharField(
                blank=True,
                choices=[
                    ("studio", "Studio"),
                    ("1_bhk", "1 BHK"),
                    ("2_bhk", "2 BHK"),
                    ("3_bhk", "3 BHK"),
                    ("4_bhk", "4 BHK"),
                    ("4_plus_bhk", "4+ BHK"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="lead",
            name="preferred_location",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
