# Generated by Django 5.2.16 on 2026-07-19 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leads", "0003_lead_budget_max_lead_budget_min_lead_preferred_bhk_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lead",
            name="source",
            field=models.CharField(
                choices=[
                    ("website", "Website"),
                    ("referral", "Referral"),
                    ("google", "Google"),
                    ("manual", "Manual"),
                    ("whatsapp", "WhatsApp"),
                    ("import", "Import"),
                ],
                default="manual",
                max_length=20,
            ),
        ),
    ]
